id: https://open-and-sustainable.github.io/revaise-model/schema/objects/base
name: revaise_objects
description: "Aggregator for RevAIse object modules."
imports:
  - ./enums
  - ./slots
  - ./review
  - ./protocol
  - ./stage_execution
  - ./ai_use
  - ./provider
  - ./model
  - ./prompt
  - ./artifact
  - ./human_loop
  - ./decision
  - ./output
  - ./prisma
  - ./synthesis
  - ./metric
  - ./software_env
  - ./agent
