site_name: RevAIse Data Model
site_url: https://revaise-model.readthedocs.io
site_description: A LinkML schema for AI-assisted systematic literature reviews
site_author: RevAIse Contributors

repo_url: https://github.com/open-and-sustainable/revaise-model
repo_name: open-and-sustainable/revaise-model
edit_uri: edit/main/docs/

# Theme configuration
theme:
    name: material
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: blue
          accent: indigo
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: blue
          accent: indigo
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    features:
        - content.code.copy
        - content.code.annotate
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.expand
        - navigation.top
        - search.suggest
        - search.highlight
        - search.share
        - toc.follow
    icon:
        repo: fontawesome/brands/github
    logo: assets/favicon.ico
    favicon: assets/favicon.ico

# Navigation
nav:
    - Home: index.md
    - Schema:
          - Overview: schema/index.md
          - Main Schema: schema/main/
          - Review Core Objects:
                - Review: schema/objects/review/
                - Author: schema/objects/author/
                - Protocol: schema/objects/protocol/
                - Literature Record: schema/objects/literature_record/
          - Shared Infrastructure:
                - Registration Template: schema/objects/registration_template/
                - Stage Execution: schema/objects/stage_execution/
                - Stage Output: schema/objects/stage_output/
                - Software Environment: schema/objects/software_env/
                - External Tool: schema/objects/external_tool/
                - Enums: schema/objects/enums/
          - Additional Objects:
                - Stage Protocol: schema/objects/stage_protocol/
                - Stage Quality Control: schema/objects/stage_quality_control/
                - Stage Statistics: schema/objects/stage_statistics/
                - AI Assistance: schema/objects/ai_assistance/
                - Conflict Resolution: schema/objects/conflict_resolution/
                - Field Definition: schema/objects/field_definition/
                - Participant: schema/objects/participant/
                - Quality Assessment: schema/objects/quality_assessment/
                - Quality Metrics: schema/objects/quality_metrics/
                - Work Session: schema/objects/work_session/
          - Stages:
                - Synthesis: schema/stages/synthesis/
                - Registration: schema/stages/registration/
                - Search: schema/stages/search/
                - Screening: schema/stages/screening/
                - Extraction: schema/stages/extraction/
                - Synthesis: schema/stages/synthesis/
    - API:
          - JSON Schema: api/revaise.schema.json
          - JSON-LD Context: api/context.jsonld
    - License: https://github.com/open-and-sustainable/revaise-model/blob/main/LICENSE
    - Changelog: https://github.com/open-and-sustainable/revaise-model/blob/main/CHANGELOG.md
    - Citation: https://github.com/open-and-sustainable/revaise-model/blob/main/CITATION.cff

# Plugins
plugins:
    - search:
          lang: en
    - tags
    - macros:
          module_name: docs/hooks/readthedocs_version

# Hooks for custom functionality (alternative to macros plugin)
# hooks:
#     - docs/hooks/readthedocs_version.py

# Markdown extensions
markdown_extensions:
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - md_in_html
    - toc:
          permalink: true
          toc_depth: 3
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
    - tables

# Extra configuration
extra:
    # Version information - populated by ReadTheDocs hook
    version: "latest" # Default value, overridden by hook
    # Social links
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/open-and-sustainable/revaise-model
          name: GitHub Repository
    # Generator notice
    generator: false

# CSS and JavaScript customization
extra_css:
    - stylesheets/extra.css
    - stylesheets/logo.css

# Copyright
copyright: Copyright &copy; 2025 RevAIse Contributors - CC0 1.0 Universal
