name: Build & Deploy

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install LinkML toolchain
        run: |
          python -m pip install --upgrade pip
          pip install linkml linkml-runtime linkml-renderer jsonschema jq
      - name: Determine version
        id: v
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "ver=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
          else
            echo "ver=dev" >> $GITHUB_OUTPUT
          fi
      - name: Build site
        run: bash scripts/build.sh "${{ steps.v.outputs.ver }}"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
